# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionCode',
            fields=[
                ('code', models.IntegerField(primary_key='True', serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'conditionCode',
                'verbose_name': 'Condition Code',
                'verbose_name_plural': 'Condition Codes',
            },
        ),
        migrations.CreateModel(
            name='IrrigationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'irrigationSchedule',
                'verbose_name': 'Irrigation Schedule',
                'verbose_name_plural': 'Irrigation Schedules',
            },
        ),
        migrations.CreateModel(
            name='IrrigationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemState', models.IntegerField(db_column='system_state')),
            ],
            options={
                'db_table': 'irrigation_system',
                'verbose_name': 'Irrigation System',
                'verbose_name_plural': 'Irrigation System',
            },
        ),
        migrations.CreateModel(
            name='RpiGpio',
            fields=[
                ('rpiGpioId', models.IntegerField(primary_key='True', serialize=False)),
                ('gpioName', models.CharField(max_length=45)),
                ('gpioNumber', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'rpiGpio',
                'verbose_name': 'RPI GPIO',
                'verbose_name_plural': 'RPI GPIO',
            },
        ),
        migrations.CreateModel(
            name='RpiGpioRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onDateTime', models.DateTimeField()),
                ('offDateTime', models.DateTimeField()),
                ('rpiGpio', models.ForeignKey(db_column='rpiGpioId', on_delete=django.db.models.deletion.CASCADE, to='sprinklesmart.RpiGpio')),
            ],
            options={
                'db_table': 'rpiGpioRequest',
                'verbose_name': 'RPI GPIO Request',
                'verbose_name_plural': 'RPI GPIO Requests',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleId', models.IntegerField(primary_key='True', serialize=False)),
                ('shortName', models.CharField(max_length=45)),
                ('displayName', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('startTime', models.TimeField()),
            ],
            options={
                'db_table': 'schedule',
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusId', models.IntegerField(primary_key='True', serialize=False)),
                ('shortName', models.CharField(max_length=45)),
                ('displayName', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'status',
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditionDateTime', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conditionCode', models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.CASCADE, to='sprinklesmart.ConditionCode')),
            ],
            options={
                'db_table': 'weatherCondition',
                'verbose_name': 'Weather Condition',
                'verbose_name_plural': 'Weather Conditions',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('weekDayId', models.IntegerField(primary_key='True', serialize=False)),
                ('shortName', models.CharField(max_length=10)),
                ('longName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'weekday',
                'verbose_name': 'Week Day',
                'verbose_name_plural': 'Week Days',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zoneId', models.IntegerField(primary_key='True', serialize=False)),
                ('shortName', models.CharField(max_length=45)),
                ('displayName', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('is_on', models.BooleanField(default=False)),
                ('locationName', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'zone',
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.AddField(
            model_name='rpigpiorequest',
            name='status',
            field=models.ForeignKey(db_column='statusId', on_delete=django.db.models.deletion.CASCADE, to='sprinklesmart.Status'),
        ),
        migrations.AddField(
            model_name='rpigpio',
            name='zone',
            field=models.ForeignKey(db_column='zoneId', on_delete=django.db.models.deletion.CASCADE, to='sprinklesmart.Zone'),
        ),
        migrations.AddField(
            model_name='irrigationschedule',
            name='schedule',
            field=models.ForeignKey(db_column='scheduleId', on_delete=django.db.models.deletion.CASCADE, to='sprinklesmart.Schedule'),
        ),
        migrations.AddField(
            model_name='irrigationschedule',
            name='weekDays',
            field=models.ManyToManyField(to='sprinklesmart.WeekDay'),
        ),
        migrations.AddField(
            model_name='irrigationschedule',
            name='zone',
            field=models.ForeignKey(db_column='zoneId', on_delete=django.db.models.deletion.CASCADE, to='sprinklesmart.Zone'),
        ),
    ]
