# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklesmart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathercondition',
            name='forecastDay1',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='weathercondition',
            name='forecastDay2',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='weathercondition',
            name='forecastDay3',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='weathercondition',
            name='forecastDay4',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='weathercondition',
            name='forecastDay5',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='weathercondition',
            name='title',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='weathercondition',
            name='unitOfMeasure',
            field=models.CharField(default='F', max_length=10),
        ),
    ]
