# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklesmart', '0003_irrigationschedule_sortorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekday',
            name='weekDay',
            field=models.IntegerField(default=0),
        ),
    ]
