# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklesmart', '0004_weekday_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpigpiorequest',
            name='durationMultiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
