# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklesmart', '0005_rpigpiorequest_durationmultiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationsystem',
            name='systemState',
            field=models.BooleanField(db_column='system_state'),
        ),
    ]
