# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklesmart', '0006_auto_20171126_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
