# Generated by Django 2.2.7 on 2020-01-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklesmart', '0008_zone_sortorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='irrigationschedule',
            options={'ordering': ['sortOrder'], 'verbose_name': 'Irrigation Schedule', 'verbose_name_plural': 'Irrigation Schedules'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['sortOrder'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AddField(
            model_name='zone',
            name='disabledDisplayText',
            field=models.CharField(blank=True, default='Off', max_length=255, verbose_name='Text to display when enabled is False'),
        ),
        migrations.AddField(
            model_name='zone',
            name='enabledDisplayText',
            field=models.CharField(blank=True, default='On', max_length=255, verbose_name='Text to display when enabled is True'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='schedule',
            field=models.ForeignKey(db_column='scheduleId', on_delete=django.db.models.deletion.PROTECT, to='sprinklesmart.Schedule'),
        ),
        migrations.AlterField(
            model_name='irrigationschedule',
            name='zone',
            field=models.ForeignKey(db_column='zoneId', on_delete=django.db.models.deletion.PROTECT, to='sprinklesmart.Zone'),
        ),
        migrations.AlterField(
            model_name='rpigpio',
            name='zone',
            field=models.ForeignKey(db_column='zoneId', on_delete=django.db.models.deletion.PROTECT, to='sprinklesmart.Zone'),
        ),
        migrations.AlterField(
            model_name='rpigpiorequest',
            name='rpiGpio',
            field=models.ForeignKey(db_column='rpiGpioId', on_delete=django.db.models.deletion.PROTECT, to='sprinklesmart.RpiGpio'),
        ),
        migrations.AlterField(
            model_name='rpigpiorequest',
            name='status',
            field=models.ForeignKey(db_column='statusId', on_delete=django.db.models.deletion.PROTECT, to='sprinklesmart.Status'),
        ),
        migrations.AlterField(
            model_name='weathercondition',
            name='conditionCode',
            field=models.ForeignKey(db_column='code', on_delete=django.db.models.deletion.PROTECT, to='sprinklesmart.ConditionCode'),
        ),
    ]
