# Generated by Django 2.2.7 on 2020-01-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklesmart', '0009_auto_20200126_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='disabledDisplayText',
            new_name='offDisplayText',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='enabledDisplayText',
            new_name='onDisplayText',
        ),
    ]
