# Generated by Django 2.2.7 on 2020-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklesmart', '0010_auto_20200126_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='offDisplayText',
            field=models.CharField(blank=True, default='Off', max_length=255, verbose_name='Text to display when OFF'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='onDisplayText',
            field=models.CharField(blank=True, default='On', max_length=255, verbose_name='Text to display when ON'),
        ),
    ]
