# Generated by Django 2.2.7 on 2020-02-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklesmart', '0012_auto_20200202_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationsystem',
            name='system_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sprinklesmart.SystemMode'),
            preserve_default=False,
        ),
    ]
