# Generated by Django 2.2.7 on 2020-02-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklesmart', '0013_irrigationsystem_system_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationsystem',
            name='system_zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sprinklesmart.Zone'),
            preserve_default=False,
        ),
    ]
